SECURITYSESSIONID=186a8
USER=moichou
MallocNanoZone=0
COMMAND_MODE=unix2003
PATH=/Users/moichou/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/moichou/.brew/bin
HOME=/Users/moichou
SHELL=/bin/minishell
LaunchInstanceID=139516FA-9B01-49F6-AF53-0ADF68815AFC
__CF_USER_TEXT_ENCODING=0x19230:0x0:0x0
XPC_SERVICE_NAME=0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.GEBNUVNzGa/Listeners
XPC_FLAGS=0x0
LOGNAME=moichou
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000ck600034jh/T/
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=2
PWD=/Users/moichou/Desktop/minishell
OLDPWD=/Users/moichou/Desktop/minishell
ZSH=/Users/moichou/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=di
HOMEBREW_CACHE=/tmp/moichou/Homebrew/Caches
HOMEBREW_TEMP=/tmp/moichou/Homebrew/Temp
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.83.1
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000ck600034jh/T/vscode-git-21d44b75e4.sock
VSCODE_INJECTION=1
ZDOTDIR=/Users/moichou
USER_ZDOTDIR=/Users/moichou
TERM=xterm-256color
_=env
a=ls   -la
